image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup RStudio Server
    init: |
      # Use a predefined username
      USERNAME=sih-notebook

      # Create the user without a password
      sudo useradd -m -s /bin/bash $USERNAME
      sudo usermod -aG sudo $USERNAME

      # Configure RStudio Server to disable authentication
      sudo sed -i '/^#auth-none=0$/a auth-none=1' /etc/rstudio/rserver.conf
      sudo sed -i '/^#www-frame-origin/s/^#//' /etc/rstudio/rserver.conf

      # Start RStudio Server
      sudo rstudio-server start

  - name: Open RStudio
    command: |
      # Wait for RStudio Server to start and then open it in the browser
      gp ports await 8787 && gp preview $(gp url 8787) --external

ports:
  - port: 8787
    onOpen: notify
    visibility: public
