image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup RStudio Server
    init: |
      # Ensure environment variables for username and password are set
      : "${USERNAME:?Need to set USERNAME}"
      : "${PASSWORD:?Need to set PASSWORD}"

      # Create the user with the provided username and password
      sudo useradd -m -s /bin/bash $USERNAME
      echo "$USERNAME:$PASSWORD" | sudo chpasswd
      sudo usermod -aG sudo $USERNAME

      # Start RStudio Server
      sudo rstudio-server start

  - name: Open RStudio
    command: gp preview $(gp url 8787) --external

ports:
  - port: 8787
    onOpen: notify
    visibility: public