image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup RStudio Server
    init: |
      # Use a predefined username
      USERNAME=sih-rnaseq

      # Prompt the user to set their own password
      echo "Please enter a password for the RStudio Server:"
      read -s PASSWORD

      # Create the user with the provided password
      sudo useradd -m -s /bin/bash $USERNAME
      echo "$USERNAME:$PASSWORD" | sudo chpasswd
      sudo usermod -aG sudo $USERNAME

      # Start RStudio Server
      sudo rstudio-server start

  - name: Open RStudio
    command: |
      # Wait for RStudio Server to start and then open it in the browser
      gp ports await 8787 && gp preview $(gp url 8787) --external

ports:
  - port: 8787
    onOpen: notify
    visibility: public
